version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "mothly"      
  - package-ecosystem: "nuget"
    directory: "/code/"
    schedule:
      interval: "weekly"  
